### ISSUE TITLE
Spinner/progress, terminal line breaking in Windows (GitBash / Shell), Cygwin okay

### ISSUE THREAD

**Issue by danielweck** [chriso/cli#64]
On Windows with GitBash / GitShell there are line breaks after each progress message, which spams the terminal with unnecessary text :( 
(even when using `process.stderr.write()`)
That's because `'\u000D'` is not processed correctly in the terminal (see in https://github.com/chriso/cli/blob/master/cli.js )
This works fine in Cygwin though.

Note that https://github.com/tj/node-progress works fine because it uses the `process.stderr.clearLine/write/cursorTo()` API. See: https://github.com/tj/node-progress/blob/master/lib/node-progress.js#L140

**Comment by chriso** [comment]
Fixed in `0.6.6`.
