### ISSUE TITLE
Piping conflicts with spinner

### ISSUE THREAD

**Issue by jrsmith17** [chriso/cli#67]
I hit an issue while trying to pipe out to a text file. Our codebase is also using a spinner from the CLI library. I believe that I'm not in a position to share code, but here's the error dump I got:

vagrant@precise64:/vagrant/flh-etl$ node index > output.txt

/vagrant/flh-etl/modules/commandLineInterface/node_modules/cli/cli.js:1147
        stream.clearLine();
               ^
TypeError: Object #<SyncWriteStream> has no method 'clearLine'
    at null.<anonymous> (/vagrant/flh-etl/modules/commandLineInterface/node_modules/cli/cli.js:1147:16)
    at wrapper [as _onTimeout] (timers.js:258:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by KodeAndGame** [comment]
Can reproduce issue with the spinner example: https://github.com/chriso/cli/blob/master/examples/spinner.js
